# Generated by Django 3.2.8 on 2021-11-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20211104_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
