# Generated by Django 3.2.8 on 2021-11-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_orderlineitem_lineitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.SlugField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.SlugField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.SlugField(default=0),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.SlugField(default=0),
        ),
    ]
