# Generated by Django 3.2.8 on 2021-11-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20211104_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='size',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
