# Generated by Django 3.2.8 on 2021-10-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
