# Generated by Django 3.2.8 on 2021-10-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
